import test from "node:test";
import assert from "node:assert/strict";
import { databaseQuery } from "../src/lib/database-gateway";
import {
  catalogQuery,
  executeSql,
  mutateRow,
  tableInfo,
} from "../src/lib/database-editor";

// Requires two isolated db+meta stacks in supabase-projects/editor-qa-{a,b}/docker.
test(
  "Private database editor: isolation, typed CRUD, conflicts, SQL limits and timeout",
  { skip: process.env.DATABASE_EDITOR_INTEGRATION !== "1" },
  async () => {
    const a = "editor-qa-a",
      b = "editor-qa-b";
    const name = "editor_test";
    try {
      for (const slug of [a, b]) {
        await databaseQuery(
          slug,
          `CREATE TABLE public.${name} (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text, amount numeric(30,8), created_at timestamptz DEFAULT now(), payload jsonb, enabled boolean DEFAULT true)`,
        );
      }
      const unicode = "🙂 café 漢字".repeat(4000);
    assert.equal((await databaseQuery(a, "SELECT $1::text AS value", [unicode]))[0].value, unicode);
    const tables = await databaseQuery(a, catalogQuery);
      const id = String(tables.find((t) => t.name === name)!.id);
      assert.equal((await tableInfo(a, id)).primary_keys[0], "id");
      const [first] = await mutateRow(
        a,
        id,
        "insert",
        {
          title: "O'Reilly \\ $1 ; DROP TABLE editor_test; --",
          amount: "123456789012345678901.12345678",
          payload: { hello: "world" },
        },
        undefined,
        undefined,
      );
      assert.equal(first.amount, "123456789012345678901.12345678");
      assert.equal(
        (await databaseQuery(b, `SELECT * FROM public.${name}`)).length,
        0,
      );
      const [updated] = await mutateRow(
        a,
        id,
        "update",
        { title: "Updated" },
        { id: first.id },
        first,
      );
      assert.equal(updated.title, "Updated");
      await assert.rejects(
        () =>
          mutateRow(
            a,
            id,
            "update",
            { title: "stale" },
            { id: first.id },
            first,
          ),
        /registro mudou/,
      );
      await assert.rejects(
        () => mutateRow(a, id, "delete", {}, {}, updated),
        /Chave primária/,
      );
      await mutateRow(a, id, "delete", {}, { id: updated.id }, updated);
      assert.equal(
        (await databaseQuery(a, `SELECT * FROM public.${name}`)).length,
        0,
      );
      const result = await executeSql(
        a,
        "select generate_series(1,400) as number;",
      );
      assert.equal(result.rows.length, 200);
      assert.equal(result.truncated, true);
      await assert.rejects(
        () => executeSql(a, "select 1; select 2;"),
        /uma instrução/,
      );
      const preview = await executeSql(
        a,
        `INSERT INTO public.${name}(title) VALUES ('requires confirmation')`,
      );
      assert.equal(preview.requiresConfirmation, true);
      assert.equal(
        (await databaseQuery(a, `SELECT * FROM public.${name}`)).length,
        0,
      );
      await executeSql(
        a,
        `INSERT INTO public.${name}(title) VALUES ('confirmed')`,
        true,
      );
      assert.equal(
        (await databaseQuery(a, `SELECT * FROM public.${name}`)).length,
        1,
      );
      await assert.rejects(
        () => executeSql(a, "select pg_sleep(15)"),
        /timeout/,
      );
    } finally {
      for (const slug of [a, b])
        await databaseQuery(slug, `DROP TABLE IF EXISTS public.${name}`);
    }
  },
);
