import { NextRequest, NextResponse } from "next/server";
import { validateSession } from "@/lib/auth";
import { findInstance } from "@/lib/companies";
import {
  catalogQuery,
  executeSql,
  identifier,
  mutateRow,
  tableInfo,
} from "@/lib/database-editor";
import { databaseQuery, DatabaseError } from "@/lib/database-gateway";

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const session = await validateSession(
    request.cookies.get("session")?.value || "",
  );
  if (!session)
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const instance = await findInstance((await params).id, session.user.id);
  if (!instance)
    return NextResponse.json(
      { error: "Instância não encontrada ou sem permissão." },
      { status: 404 },
    );
  try {
    const raw = await request.text();
    if (Buffer.byteLength(raw) > 100000)
      throw new DatabaseError("Operação excede 100 KB.", 413);
    const input = JSON.parse(raw);
    let result: unknown;
    if (input.action === "tables")
      result = { tables: await databaseQuery(instance.slug, catalogQuery) };
    else if (input.action === "rows") {
      if (typeof input.tableId !== "string")
        throw new DatabaseError("Tabela inválida.");
      const table = await tableInfo(instance.slug, input.tableId);
      const page = Number(input.page ?? 0);
      if (!Number.isSafeInteger(page) || page < 0 || page > 10000)
        throw new DatabaseError("Página inválida.");
      const order = table.primary_keys.length
        ? ` ORDER BY ${table.primary_keys.map(identifier).join(",")}`
        : "";
      const rows = await databaseQuery(
        instance.slug,
        `SELECT * FROM ${identifier(table.schema)}.${identifier(table.name)}${order} LIMIT 51 OFFSET $1`,
        [page * 50],
      );
      result = { table, rows: rows.slice(0, 50), hasMore: rows.length > 50 };
    } else if (["insert", "update", "delete"].includes(input.action)) {
      if (typeof input.tableId !== "string")
        throw new DatabaseError("Tabela inválida.");
      result = {
        rows: await mutateRow(
          instance.slug,
          input.tableId,
          input.action,
          input.values,
          input.key,
          input.original,
        ),
      };
    } else if (input.action === "create-table") {
      if (
        typeof input.name !== "string" ||
        !Array.isArray(input.columns) ||
        input.columns.length > 30
      )
        throw new DatabaseError("Definição de tabela inválida.");
      const types = new Set([
        "text",
        "bigint",
        "numeric",
        "boolean",
        "timestamptz",
        "jsonb",
        "uuid",
      ]);
      const seen = new Set(["id", "created_at"]);
      const columns = input.columns.map(
        (column: { name: string; type: string }) => {
          if (
            typeof column?.name !== "string" ||
            !types.has(column.type) ||
            seen.has(column.name)
          )
            throw new DatabaseError("Colunas inválidas ou duplicadas.");
          seen.add(column.name);
          return `${identifier(column.name)} ${column.type}`;
        },
      );
      await databaseQuery(
        instance.slug,
        `BEGIN; CREATE TABLE public.${identifier(input.name)} (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now()${columns.length ? "," + columns.join(",") : ""}); ALTER TABLE public.${identifier(input.name)} ENABLE ROW LEVEL SECURITY; COMMIT;`,
      );
      result = { success: true };
    } else if (input.action === "sql") {
      if (typeof input.sql !== "string")
        throw new DatabaseError("SQL inválido.");
      result = await executeSql(
        instance.slug,
        input.sql,
        input.confirmed === true,
      );
    } else throw new DatabaseError("Operação inválida.");
    return NextResponse.json(result, {
      headers: { "Cache-Control": "no-store" },
    });
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof DatabaseError
            ? error.message
            : "Não foi possível concluir a operação no banco.",
      },
      {
        status: error instanceof DatabaseError ? error.status : 400,
        headers: { "Cache-Control": "no-store" },
      },
    );
  }
}
